name: CI

on:
  push:
    tags:
      - ci

env:
  ENV_FILE: ${{ secrets.ENV_CI }}

jobs:
  build:
    name: 'Build'

    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'
      - run: npm ci
      - name: 'Create .env file'
        run: |
          echo "${{ env.ENV_FILE }}" > .env
      - run: npm run build

  test:
    name: 'Test'

    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'
      - run: npm ci
      - name: 'Create .env file'
        run: |
          echo "${{ env.ENV_FILE }}" > .env
      - run: npm run test

  scan:
    name: 'Sonarqube'
    uses: mwarman/.github/.github/workflows/sonarqube-scan.yml@main
    secrets:
      SONAR_HOST_URL: 'https://mwarman.sonarqube.com'
      SONAR_TOKEN: 'hello-i-am-a-token'
